summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-ppc64le/releases/download/2023.06.22/pkg-config-0.29.2-linux-ppc64le.tar.xz 
bin-sha: 3e7e500cb329829c586561a51002fc4be579f90b98eac7e1de8b6c75de89a690
